//! Golden-fixture conformance between the Python exporter and the Rust reader.
//!
//! The fixtures and their `.expected.json` sidecars are generated by
//! `rai-infer/scripts/test_raimodel.py` (`write_minimal_model`) from the same
//! arrays the writer packed, so any drift in header layout, section assembly,
//! nibble order, or group-parameter layout between the two implementations
//! fails here instead of silently corrupting real exports.

use std::path::{Path, PathBuf};

use half::f16;
use rai_infer::format::{QuantizedEmbedding, QuantizedLinear, RaiModelFile};
use serde_json::Value;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn load_sidecar(name: &str) -> Value {
    let text = std::fs::read_to_string(fixture(name)).expect("read sidecar");
    serde_json::from_str(&text).expect("parse sidecar")
}

fn expected_f32s(sidecar: &Value, key: &str) -> Vec<f32> {
    sidecar["expected"][key]
        .as_array()
        .unwrap_or_else(|| panic!("sidecar missing expected.{key}"))
        .iter()
        .map(|v| v.as_f64().expect("numeric expected value") as f32)
        .collect()
}

fn group_param(params: &[u8], row: usize, num_groups: usize, group: usize) -> (f32, f32) {
    let base = (row * num_groups + group) * 4;
    let scale = f16::from_le_bytes([params[base], params[base + 1]]).to_f32();
    let zero = f16::from_le_bytes([params[base + 2], params[base + 3]]).to_f32();
    (scale, zero)
}

fn dequant_linear_row_prefix(linear: &QuantizedLinear, row: usize, count: usize) -> Vec<f32> {
    let num_groups = linear.cols.div_ceil(linear.group_size);
    let row_bytes = linear.cols / 2;
    (0..count)
        .map(|col| {
            let (scale, zero) = group_param(
                linear.group_params,
                row,
                num_groups,
                col / linear.group_size,
            );
            let byte = linear.nibble_data[row * row_bytes + col / 2];
            let code = if col % 2 == 0 { byte & 0x0F } else { byte >> 4 };
            f32::from(code) * scale + zero
        })
        .collect()
}

fn dequant_embedding_row(embedding: &QuantizedEmbedding, row: usize) -> Vec<f32> {
    let num_groups = embedding.hidden_size.div_ceil(embedding.group_size);
    (0..embedding.hidden_size)
        .map(|col| {
            let (scale, zero) = group_param(
                embedding.group_params,
                row,
                num_groups,
                col / embedding.group_size,
            );
            let code = embedding.data[row * embedding.hidden_size + col];
            f32::from(code) * scale + zero
        })
        .collect()
}

fn assert_close(actual: &[f32], expected: &[f32], what: &str) {
    assert_eq!(actual.len(), expected.len(), "{what}: length mismatch");
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        let tolerance = f32::EPSILON * e.abs().max(1.0);
        assert!(
            (a - e).abs() <= tolerance,
            "{what}[{i}]: reader dequantized {a}, exporter recorded {e}"
        );
    }
}

fn check_config(file: &RaiModelFile, sidecar: &Value) {
    let cfg = &sidecar["config"];
    let c = &file.config;
    assert_eq!(
        u64::from(c.hidden_size),
        cfg["hidden_size"].as_u64().unwrap()
    );
    assert_eq!(u64::from(c.num_layers), cfg["num_layers"].as_u64().unwrap());
    assert_eq!(u64::from(c.num_heads), cfg["num_heads"].as_u64().unwrap());
    assert_eq!(
        u64::from(c.num_kv_heads),
        cfg["num_kv_heads"].as_u64().unwrap()
    );
    assert_eq!(u64::from(c.head_dim), cfg["head_dim"].as_u64().unwrap());
    assert_eq!(
        u64::from(c.intermediate_size),
        cfg["intermediate_size"].as_u64().unwrap()
    );
    assert_eq!(u64::from(c.vocab_size), cfg["vocab_size"].as_u64().unwrap());
    assert_eq!(
        u64::from(c.max_context),
        cfg["max_context"].as_u64().unwrap()
    );
    assert_eq!(f64::from(c.rope_theta), cfg["rope_theta"].as_f64().unwrap());
    assert!((f64::from(c.norm_eps) - cfg["norm_eps"].as_f64().unwrap()).abs() < 1e-12);
    assert_eq!(u64::from(c.bits), cfg["bits"].as_u64().unwrap());
    assert_eq!(u64::from(c.group_size), cfg["group_size"].as_u64().unwrap());
    assert_eq!(u64::from(c.embed_bits), cfg["embed_bits"].as_u64().unwrap());
    assert_eq!(
        u64::from(c.embed_group_size),
        cfg["embed_group_size"].as_u64().unwrap()
    );
}

fn run_fixture(model_name: &str, sidecar_name: &str) {
    let sidecar = load_sidecar(sidecar_name);
    let path = fixture(model_name);

    let file_size = std::fs::metadata(&path).expect("fixture metadata").len();
    assert_eq!(
        file_size,
        sidecar["file_size"].as_u64().unwrap(),
        "file size"
    );

    let file = RaiModelFile::open(&path).expect("reader must accept the exporter's output");
    check_config(&file, &sidecar);
    assert_eq!(
        file.sections.len() as u64,
        sidecar["num_sections"].as_u64().unwrap(),
        "section count"
    );

    let tied = sidecar["tied"].as_bool().unwrap();
    assert_eq!(file.has_lm_head(), !tied, "tied/untied detection");

    let embedding = file.embedding().expect("embedding section");
    assert_close(
        &dequant_embedding_row(&embedding, 0),
        &expected_f32s(&sidecar, "embedding_row0"),
        "embedding row 0",
    );

    let layer0 = file.layer(0).expect("layer 0");
    assert_close(
        &dequant_linear_row_prefix(&layer0.q_proj, 0, 8),
        &expected_f32s(&sidecar, "layer0_q_proj_row0_first8"),
        "layer 0 q_proj row 0",
    );

    if !tied {
        let lm_head = file
            .lm_head()
            .expect("lm_head accessor")
            .expect("untied model must expose an lm_head section");
        assert_close(
            &dequant_linear_row_prefix(&lm_head, 0, 8),
            &expected_f32s(&sidecar, "lm_head_row0_first8"),
            "lm_head row 0",
        );
    }
}

#[test]
fn tied_fixture_matches_exporter() {
    run_fixture("tiny-tied.raimodel", "tiny-tied.expected.json");
}

#[test]
fn untied_fixture_matches_exporter() {
    run_fixture("tiny-untied.raimodel", "tiny-untied.expected.json");
}
